name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jank1096
          outputs: |
            dist/github-snake.svg?color_snake=0a0a0a&color_dots=#e6e6e6,#c0c0c0,#8a8a8a,#555555,#0a0a0a
            dist/github-snake-dark.svg?color_snake=ffffff&color_dots=#161b22,#333333,#666666,#999999,#ffffff

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
