name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jank1096
          outputs: |
            dist/github-snake.svg?color_snake=#3776AB&color_dots=#EAF4FF,#C7E2FF,#8FC5F4,#5BA3DD,#3776AB
            dist/github-snake-dark.svg?color_snake=#58A6FF&color_dots=#0D1117,#143454,#1F6FEB,#58A6FF,#A5D6FF

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
